### PR TITLE
Refactor/Update Dockerfile

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Just a few adjustments to make the Docker image even better :tada:

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hi @mrtazz, do you have a minute to take a look? Thanks.

**Comment by mrtazz** [comment]
change looks good to me. But it seems there is a conflict with the Dockerfile in the default branch

**Comment by PeterDaveHello** [comment]
Cool, looks like there are multiple conflicts as the code base changed in the past year, I'll resolve them.

**Comment by PeterDaveHello** [comment]
Well... it's strange that I can't build the image any more, looks like something is broken during the past year...

**Comment by PeterDaveHello** [comment]
#51 sent, looks like it's a little bit messy there 😅

**Comment by PeterDaveHello** [comment]
@mrtazz conflicts resolved! Thanks.

**Comment by PeterDaveHello** [comment]
@mrtazz any chance to take a look? Thanks.

**Comment by mrtazz** [comment]
Thanks for taking the time to contribute!

**Pull request merged**
