### PR TITLE
Only print the header if there are violations to display

### PR DESCRIPTION
**Pull request by ashmckenzie**
## Checklist

This PR updates the formatter logic to only displays violations if there are any, which for the default formatter results in the headers not being printed and also removes the newlines from start/end of the content. This follows the UNIX philosophy of [no news is good news](https://en.wikipedia.org/wiki/Talk%3AUnix_philosophy#No_news_is_good_news) 🙂

e.g.

**Before**

With violations:

```sh
$ ./checkmake Makefile

      RULE                 DESCRIPTION             LINE NUMBER

  minphony        Missing required phony target    0
                  "all"
  minphony        Missing required phony target    0
                  "clean"
  minphony        Missing required phony target    0
                  "test"
  phonydeclared   Target "all" should be           67
                  declared PHONY.
  phonydeclared   Target "binaries" should be      70
                  declared PHONY.
  phonydeclared   Target "install" should be               103
                  declared PHONY.
  phonydeclared   Target "packages" should be              109
                  declared PHONY.

```

Without violations:

```
$ ./checkmake Makefile

  RULE   DESCRIPTION   LINE NUMBER

$ ./checkmake Makefile | wc -l
       4
```

**After**

With violations:

```sh
$ ./checkmake Makefile
      RULE                 DESCRIPTION             LINE NUMBER

  minphony        Missing required phony target    0
                  "all"
  minphony        Missing required phony target    0
                  "clean"
  minphony        Missing required phony target    0
                  "test"
  phonydeclared   Target "all" should be           67
                  declared PHONY.
  phonydeclared   Target "binaries" should be      70
                  declared PHONY.
  phonydeclared   Target "install" should be               103
                  declared PHONY.
  phonydeclared   Target "packages" should be              109
                  declared PHONY.
```

Without violations:

```sh
$ ./checkmake Makefile
$ ./checkmake Makefile | wc -l
       0
```

- [ ] CI passes
- [x] Description of proposed change
- [ ] Documentation (README, docs/, man pages) is updated
- [ ] Existing issue is referenced if there is one
- [ ] Unit tests for the proposed change

### CODE REVIEW

**Comment by ashmckenzie** [comment]
@mrtazz for your consideration 🙂

**Comment by ashmckenzie** [comment]
For reference, we're using it at https://gitlab.com/gitlab-org/gitlab-development-kit/-/merge_requests/1911 🙂

**Comment by ashmckenzie** [comment]
Thoughts @mrtazz ?

**Comment by ashmckenzie** [comment]
Ping @mrtazz ?

**Comment by mrtazz** [comment]
Thanks for the contribution!

**Pull request merged**
